### ISSUE TITLE
centos 7 can not run epserver

### ISSUE THREAD

**Issue by lizihan8** [mtcp-stack/mtcp#233]
I am trying to run epserver on centos 7 on VM   mtcp relese v2.1. When i use this command to run the server
./run_single_process.sh 
Configuration updated by mtcp_setconf().
[ mtcp_init:1494] Setting mtcp_max_fds to: 1024
---------------------------------------------------------------------------------
Loading mtcp configuration from : epserver.conf
Loading interface setting
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
Total number of attached devices: 1
Interface name: dpdk0
EAL: Auto-detected process type: PRIMARY
Configurations:
Number of CPU cores available: 1
Number of CPU cores to use: 1
Maximum number of concurrency per core: 8192
Maximum number of preallocated buffers per core: 8192
Receive buffer size: 8192
Send buffer size: 8192
TCP timeout seconds: 30
TCP timewait seconds: 0
NICs to print statistics: dpdk0
---------------------------------------------------------------------------------
Interfaces:
name: dpdk0, ifindex: 0, hwaddr: 00:0C:29:AA:90:AC, ipaddr: 192.168.250.196, netmask: 255.255.255.0
Number of NIC queues: 1
---------------------------------------------------------------------------------
Loading routing configurations from : config/route.conf
Routes:
Destination: 192.168.250.0/24, Mask: 255.255.255.0, Masked: 192.168.250.0, Route: ifdx-0
Destination: 192.168.250.1/24, Mask: 255.255.255.0, Masked: 192.168.250.0, Route: ifdx-0
---------------------------------------------------------------------------------
Loading ARP table from : config/arp.conf
ARP Table:
IP addr: 192.168.250.1, dst_hwaddr: 80:B5:75:5A:89:0E
---------------------------------------------------------------------------------
Initializing port 0... ethdev port_id=0 requested Rx offloads 0x100e doesn't match Rx offloads capabilities 0x281f in rte_eth_dev_configure()

EAL: Error - exiting with code: 1
  Cause: rte_eth_tx_queue_setup:err=-22, port=0, queueid: 0
[mtcp_destroy:1596] All MTCP threads are joined.

**Comment by ajamshed** [comment]
@lizihan8,

This looks like device initialization error. Can you please check whether example dpdk applications are running fine?

**Comment by lizihan8** [comment]
@ajamshed ，
Thank you.
