### ISSUE TITLE
What is the main reason to use mtcp?

### ISSUE THREAD

**Issue by Gymmasssorla** [mtcp-stack/mtcp#250]
I guess that the main reason is the performance, because mtcp uses DPDK and netmap (libraries for fast packet transmission), is it?

**Comment by Gymmasssorla** [comment]
And are there any benchmarks with the standard Unix networking stack? Is mtcp faster?

**Comment by ajamshed** [comment]
@Gymmasssorla ,

Please see issue #248 .

**Comment by Gymmasssorla** [comment]
Thank you, now it's clear for me.
