### ISSUE TITLE
Few general questions about the network stack

### ISSUE THREAD

**Issue by freak82** [mtcp-stack/mtcp#275]
Hi there,

I'd like to ask the following questions:
1. Are there any known missing features from your TCP/IP stack?
2. Has the stack been tested against something like https://github.com/google/packetdrill.

Thanks,
Pavel.

**Comment by a-jamshed** [comment]
Hi @freak82 ,

1. Please see this [link](https://github.com/mtcp-stack/mtcp/wiki/Supported-Features) to check what features are supported/unsupported in mTCP.

2. Thanks for providing the link. We have not yet tested this stack against packetdrill. But I can try to evaluate the stack against this kit once I get free time.

**Comment by freak82** [comment]
Thanks for the quick responses.
