### ISSUE TITLE
How to connect MTCP to a DPDK vhost port?

### ISSUE THREAD

**Issue by sarsanaee** [mtcp-stack/mtcp#290]
Hi,

I want to have my MTCP sample application connected to a vhost port. However, I cannot figure out where should I config this. Should I modify the config file in the app directory? At the very end, I would like my MTCP application to use the vhost port which is actually created by my vswitch before. 

Specifically, I'd like to use `--vdev` parameter for typical DPDK applications for the MTCP sample application.

Thanks,
Alireza

**Comment by vincentmli** [comment]
> Hi,
> 
> I want to have my MTCP sample application connected to a vhost port. However, I cannot figure out where should I config this. Should I modify the config file in the app directory? At the very end, I would like my MTCP application to use the vhost port which is actually created by my vswitch before.

do you mean dpdkvhostuser ports from http://docs.openvswitch.org/en/latest/howto/dpdk/ ?

**Comment by nkarjala** [comment]
I believe something like:
testpmd  -l 4-5 -n 4 --socket-mem 512 --no-pci --file-prefix=virtio --vdev=net_virtio_user0,path=<vhost-socket-path>,queues=2,server=1 ...

**Comment by sarsanaee** [comment]
Yup, that's it, thank you @nkarjala
