### ISSUE TITLE
mTCP for Mellanox Bluefield SmartNIC

### ISSUE THREAD

**Issue by rinku-shah** [mtcp-stack/mtcp#321]
Hi,
I have a working DPDK 20.11 version running on the Mellanox Bluefield SmartNIC. 
I am unable to install mTCP on the same platform. I guess the platform to choose is "arm64_bluefield_linux_gcc" which is not available in the options.

Is mTCP supported on the Bluefield NIC hardware? If yes, could you please guide me through.

Thanks,
Rinku

**Comment by vitalif** [comment]
It's not supported by anything until you remove dpdk-iface-kmod #305
And even then it's unusable because #306

**Comment by rinku-shah** [comment]
Hey @vitalif, thanks for your response. 
Actually, I got my setup working with some mTCP code changes (mtcp-devel branch) and DPDK-19.11. I required DPDK support for ARM Bluefield architecture which starts from DPDK 19.11 onwards and the current mTCP code has been integrated until DPDK-18. I will soon post the patch here.

**Comment by CHRIS123540** [comment]
How to use MTCP in dpdk2011

**Comment by CHRIS123540** [comment]
hi,I'm also on the same platform as you, too low version of dpdk to work on bluefield.So do you currently have a way to use DPDK 20.11 in MTCP
